version: "3"
services:
    db:
        image: postgres:12.2
        container_name: ps01
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin

    web:
        build: .
        container_name: dg01
        command: bash -c "
            /src/wait-for-it.sh db:5432 -- &&
            python3 manage.py collectstatic --no-input &&
            python3 manage.py makemigrations && 
            python3 manage.py migrate && 
            gunicorn config.wsgi:application -b 0:8000"
        depends_on:
            - db
        volumes:
            - ./src:/src
            - ./wait-for-it.sh:/src/wait-for-it.sh

    nginx:
        image: nginx:1.17.10
        container_name: ng01
        ports:
            - "80:80"
        volumes:
            - ./src:/src
            - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web