# Generated by Django 5.1.4 on 2025-01-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_remove_channel_chaneel_id_channel_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='playlist_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
