# Generated by Django 5.1.4 on 2025-01-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_playlist_channel_title_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='profile_image_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
