# Generated by Django 5.1.4 on 2025-01-16 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_channel_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='Channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='scraper.channel'),
        ),
    ]
