# Generated by Django 5.1.4 on 2025-01-17 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thx_comment', models.IntegerField()),
                ('Channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scraper.channel')),
                ('Playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scraper.playlist')),
                ('Video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scraper.video')),
            ],
        ),
    ]
